name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build_libs:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y --allow-unauthenticated update
        apt -y install build-essential
        apt -y install pkg-config python-pip python-virtualenv
        apt -y install libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev valgrind

    - name: Run tests
      run: |
        make -j$(($(nproc)+1)) test
    - name: Clean
      run: |
        make -j$(($(nproc)+1)) clean
    - name: Run memory tests 
      run: |
        make -j$(($(nproc)+1)) testmem DEBUG=yes

